### PR TITLE
Chris

### PR DESCRIPTION
**Pull request by betty-crokker**
StateMachine.ToDotGraph and IStateMachineInfoFormatter removed; setters made private for members of Reflection classes and constructors added; unit tests updated

### CODE REVIEW

**Comment by psibernetic** [comment]
Was this supposed to target cartographer-api?

**Comment by betty-crokker** [comment]
Yes... Did it not?

**Comment by betty-crokker** [comment]
Am I supposed to add you as a reviewer?  Or is that implied since I'm asking you to pull it into your repository?  As I said, brand new, still trying to figure out the etiquette here.

**Comment by psibernetic** [comment]
@betty-crokker I'm just going to merge it, we can handle the reviews in the original repo.

**Comment by psibernetic** [comment]
@betty-crokker To "Merge it" I do Rebase and Merge by default, which just adds your commits to this branch directly without an extra merge commit.

**Comment by betty-crokker** [comment]
@psibernetic What's next with this PR?  Do we want to merge this back into the main repo, and update the DotGraphFormatter in a later PR?

**Pull request merged**
